language: node_js
node_js:
 - "node"
 - "8"
sudo: required
addons:
 chrome: stable
before_install:
 - google-chrome-stable --headless --disable-gpu http://localhost &
install:
 - npm install
before_script:
 - node test/echo.js &